services:
  postgres_db:
    image: postgres:16.1-bookworm
    ports:
      - "5434:5432"
    volumes:
      - awards_local_pgdata:/var/lib/postgresql/data
    env_file: .env
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: 15m
    networks:
      - awards-bridge

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    volumes:
      - ./backend:/usr/src/app
      - ./backend/collectstatic:/usr/src/app/collectstatic
      - ./backend/log:/usr/src/app/log
      - ./backend/media:/usr/src/app/media
      - ./.env:/usr/src/app/.env:ro
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - awards-bridge

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000

networks:
  awards-bridge:
    driver: bridge

volumes:
  awards_local_pgdata: {}
