# Generated by Django 5.2.5 on 2025-08-22 10:36

import django.utils.timezone
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('image', models.FileField(blank=True, default='category.jpg', null=True, upload_to='categories')),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom et prénom')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Taux de commission (%)')),
                ('affiliate_link', models.CharField(blank=True, max_length=200, unique=True, verbose_name="Lien d'affiliation")),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='project-files')),
                ('image', models.FileField(blank=True, null=True, upload_to='project-images')),
                ('project_title', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('local_area_impact', models.TextField(blank=True, max_length=1500, null=True, verbose_name="Zone géographique d'impact")),
                ('main_objective', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Objectif principal')),
                ('solution', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Problème résolu')),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Description')),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Budget estimé')),
                ('target_audience', models.TextField(blank=True, max_length=500, null=True, verbose_name='Public cible')),
                ('progress_report', models.TextField(blank=True, max_length=500, null=True, verbose_name="Etat d'avancement")),
                ('platform_status', models.CharField(choices=[('brouillon', 'Brouillon'), ('desactive', 'Désactivé'), ('rejete', 'Rejeté'), ('publie', 'Publié')], default='brouillon', max_length=100, verbose_name="L'admin défini sur :")),
                ('owner_project_status', models.CharField(choices=[('brouillon', 'Brouillon'), ('desactive', 'Désactivé'), ('publie', 'Publié')], default='brouillon', max_length=100, verbose_name="L'auteur défini sur :")),
                ('featured', models.BooleanField(default=False, verbose_name='Projet en vedette')),
                ('project_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890ABCDEF', length=8, max_length=20, prefix='', unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Commentaire admin')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, '1 Etoile'), (2, '2 Etoiles'), (3, '3 Etoiles'), (4, '4 Etoiles'), (5, '5 Etoiles')], verbose_name="Nombre d'étoile")),
                ('country_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code pays')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('active', models.BooleanField(default=False)),
                ('vote_count', models.IntegerField(default=1, verbose_name='Nombre de votes achetés')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VotePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echec', 'Échec'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VotePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField(unique=True, verbose_name='Nombre de votes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['vote_count'],
            },
        ),
    ]
