# Generated by Django 5.2.5 on 2025-10-27 17:00

import django.utils.timezone
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du clic')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='Provenance')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('converted', models.BooleanField(default=False, verbose_name='A créé un compte')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de conversion')),
            ],
            options={
                'verbose_name': "Clic d'affiliation",
                'verbose_name_plural': "Clics d'affiliation",
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('image', models.FileField(blank=True, default='category.jpg', null=True, upload_to='categories')),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890ABCDEF', length=8, max_length=20, prefix='', unique=True)),
                ('is_custom', models.BooleanField(default=False, help_text='Indique si cette catégorie a été créée par un utilisateur', verbose_name='Catégorie personnalisée')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom et prénom')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('total_clicks', models.PositiveIntegerField(default=0, verbose_name='Nombre total de clics')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Taux de commission (%)')),
                ('affiliate_link', models.CharField(blank=True, max_length=200, unique=True, verbose_name="Lien d'affiliation")),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commercial',
                'verbose_name_plural': 'Commerciaux',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='default-file-project.png', null=True, upload_to='project-files')),
                ('image', models.FileField(blank=True, default='default-image-project.jpg', null=True, upload_to='project-images')),
                ('project_title', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('local_area_impact', models.TextField(blank=True, max_length=1500, null=True, verbose_name="Zone géographique d'impact")),
                ('main_objective', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Objectif principal')),
                ('solution', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Problème résolu')),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Description')),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Budget estimé')),
                ('target_audience', models.TextField(blank=True, max_length=500, null=True, verbose_name='Public cible')),
                ('progress_report', models.TextField(blank=True, max_length=500, null=True, verbose_name="Etat d'avancement")),
                ('platform_status', models.CharField(choices=[('brouillon', 'Brouillon'), ('desactive', 'Désactivé'), ('rejete', 'Rejeté'), ('publie', 'Publié')], default='brouillon', max_length=100, verbose_name="L'admin défini sur :")),
                ('owner_project_status', models.CharField(choices=[('brouillon', 'Brouillon'), ('desactive', 'Désactivé'), ('publie', 'Publié')], default='brouillon', max_length=100, verbose_name="L'auteur défini sur :")),
                ('featured', models.BooleanField(default=False, verbose_name='Projet en vedette')),
                ('project_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890ABCDEF', length=8, max_length=20, prefix='', unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Commentaire admin')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Payé'), ('declined', 'Déclinée'), ('canceled', 'Échec')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('external_transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_reference', models.CharField(max_length=50, unique=True, verbose_name='Référence de paiement')),
                ('payer_name', models.CharField(max_length=100, verbose_name='Nom du payeur')),
                ('payer_email', models.EmailField(max_length=254, verbose_name='Email du payeur')),
                ('payer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du payeur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paiement de soumission',
                'verbose_name_plural': 'Paiements de soumissions',
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_price', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, verbose_name='Prix par soumission de projet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration soumission',
                'verbose_name_plural': 'Configurations soumissions',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(blank=True, choices=[(1, '1 Etoile'), (2, '2 Etoiles'), (3, '3 Etoiles'), (4, '4 Etoiles'), (5, '5 Etoiles')], null=True, verbose_name="Nombre d'étoile")),
                ('country_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code pays')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('voter_name', models.CharField(max_length=100, verbose_name='Nom du votant')),
                ('voter_email', models.EmailField(max_length=254, verbose_name='Email du votant')),
                ('payment_reference', models.CharField(max_length=50, verbose_name='Référence de paiement')),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('vote_count', models.IntegerField(default=1, verbose_name='Nombre de votes achetés')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VotePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Payé'), ('declined', 'Déclinée'), ('canceled', 'Échec')], default='en_attente', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VotePriceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Prix par vote')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration globale',
                'verbose_name_plural': 'Configurations globales',
            },
        ),
    ]
