# Generated by Django 5.2.5 on 2025-08-19 17:16

import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('image', models.FileField(blank=True, default='category.jpg', null=True, upload_to='categories')),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('vote', models.IntegerField(choices=[(1, '1 Vote'), (2, '2 Votes'), (4, '4 Votes'), (5, '5 Votes'), (3, '3 Votes')], default=None)),
                ('reply', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Réponse')),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='project-files')),
                ('image', models.FileField(blank=True, null=True, upload_to='project-images')),
                ('project_title', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('local_area_impact', models.TextField(blank=True, max_length=1500, null=True, verbose_name="Zone géographique d'impact")),
                ('main_objective', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Objectif principal')),
                ('solution', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Problème résolu')),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Description')),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Budget estimé')),
                ('platform_status', models.CharField(choices=[('Vote', 'Vote'), ('Publié', 'Publié'), ('Rejecté', 'Rejecté'), ('Brouillon', 'Brouillon'), ('Désactivé', 'Désactivé')], default='brouillon', max_length=100)),
                ('owner_project_status', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Désactivé', 'Désactivé'), ('Publié', 'Publié')], default='brouillon', max_length=100)),
                ('featured', models.BooleanField(default=False, verbose_name='Projet en vedette')),
                ('project_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890ABCDEF', length=8, max_length=20, prefix='', unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Commentaire admin')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category', verbose_name='Catégorie')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
