# Generated by Django 5.2.5 on 2025-09-25 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_price', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, verbose_name='Prix par soumission de projet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration soumission',
                'verbose_name_plural': 'Configurations soumissions',
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Payé'), ('declined', 'Déclinée'), ('cancel', 'Échec')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('external_transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_reference', models.CharField(max_length=50, unique=True, verbose_name='Référence de paiement')),
                ('payer_name', models.CharField(max_length=100, verbose_name='Nom du payeur')),
                ('payer_email', models.EmailField(max_length=254, verbose_name='Email du payeur')),
                ('payer_phone', models.CharField(max_length=20, verbose_name='Téléphone du payeur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_payment', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement de soumission',
                'verbose_name_plural': 'Paiements de soumissions',
            },
        ),
    ]
