# Generated by Django 5.2.5 on 2025-09-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, default='projectfile.jpg', null=True, upload_to='project-files'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, default='project.jpg', null=True, upload_to='project-images'),
        ),
    ]
