# Generated by Django 5.2.5 on 2025-10-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
        ('projectowner', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectowner.owner'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
