# Generated by Django 5.2.5 on 2025-10-03 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_category_created_by_category_is_custom'),
        ('projectowner', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_categories', to='projectowner.owner', verbose_name='Créée par'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Indique si cette catégorie a été créée par un utilisateur', verbose_name='Catégorie personnalisée'),
        ),
    ]
