# Generated by Django 5.2.5 on 2025-08-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner_project_status',
            field=models.CharField(choices=[('Brouillon', 'Brouillon'), ('Publié', 'Publié'), ('Désactivé', 'Désactivé')], default='brouillon', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='platform_status',
            field=models.CharField(choices=[('Vote', 'Vote'), ('Rejecté', 'Rejecté'), ('Brouillon', 'Brouillon'), ('Désactivé', 'Désactivé'), ('Publié', 'Publié')], default='brouillon', max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(choices=[(5, '5 Votes'), (3, '3 Votes'), (2, '2 Votes'), (1, '1 Vote'), (4, '4 Votes')], default=None),
        ),
    ]
