# Generated by Django 5.2.5 on 2025-09-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectsubmissionsettings_projectsubmissionpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmissionpayment',
            name='payer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du payeur'),
        ),
    ]
