# Generated by Django 5.2.5 on 2025-09-12 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_commercial_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercial',
            options={'verbose_name': 'Commercial', 'verbose_name_plural': 'Commerciaux'},
        ),
        migrations.AlterField(
            model_name='commercial',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
