# Generated by Django 5.2.5 on 2025-08-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_owner_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='platform_status',
            field=models.CharField(choices=[('Brouillon', 'Brouillon'), ('Publié', 'Publié'), ('Vote', 'Vote'), ('Rejecté', 'Rejecté'), ('Désactivé', 'Désactivé')], default='brouillon', max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(choices=[(2, '2 Votes'), (4, '4 Votes'), (3, '3 Votes'), (1, '1 Vote'), (5, '5 Votes')], default=None),
        ),
    ]
