# Generated by Django 5.2.5 on 2025-08-19 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_platform_status_alter_vote_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField(unique=True, verbose_name='Nombre de votes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['vote_count'],
            },
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='vote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_project_status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('desactive', 'Désactivé'), ('publie', 'Publié')], default='brouillon', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='platform_status',
            field=models.CharField(choices=[('vote', 'Vote'), ('brouillon', 'Brouillon'), ('desactive', 'Désactivé'), ('rejete', 'Rejeté'), ('valide', 'Validé'), ('publie', 'Publié')], default='brouillon', max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='Réponse'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='review',
            field=models.TextField(verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(choices=[(1, '1 Vote'), (2, '2 Votes'), (3, '3 Votes'), (4, '4 Votes'), (5, '5 Votes')], verbose_name='Note'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'project')},
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Taux de commission (%)')),
                ('affiliate_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.commercial', verbose_name='Commercial'),
        ),
        migrations.CreateModel(
            name='VotePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echec', 'Échec'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.vote')),
            ],
        ),
    ]
