# Generated by Django 5.2.5 on 2025-08-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_voteprice_rename_date_vote_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_count',
            field=models.IntegerField(default=1, verbose_name='Nombre de points'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_project_status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('desactive', 'Désactivé'), ('publie', 'Publié')], default='brouillon', max_length=100, verbose_name="Statut de l'auteur"),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='review',
        ),
    ]
