# Generated by Django 5.2.5 on 2025-08-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_vote_options_alter_vote_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress_report',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name="Etat d'avancement"),
        ),
        migrations.AddField(
            model_name='project',
            name='target_audience',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Public cible'),
        ),
    ]
