# Generated by Django 5.2.5 on 2025-08-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_progress_report_project_target_audience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial',
            name='affiliate_code',
        ),
        migrations.AddField(
            model_name='commercial',
            name='affiliate_link',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name="Lien d'affiliation"),
        ),
    ]
