# Generated by Django 5.2.5 on 2025-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_commercial_affiliate_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Nom et prénom'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
