# Generated by Django 5.2.5 on 2025-08-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_commercial_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner_project_status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('desactive', 'Désactivé'), ('publie', 'Publié')], default='brouillon', max_length=100, verbose_name="L'auteur défini sur :"),
        ),
        migrations.AlterField(
            model_name='project',
            name='platform_status',
            field=models.CharField(choices=[('vote', 'Vote'), ('brouillon', 'Brouillon'), ('desactive', 'Désactivé'), ('rejete', 'Rejeté'), ('publie', 'Publié')], default='brouillon', max_length=100, verbose_name="L'admin défini sur :"),
        ),
    ]
