# Generated by Django 5.2.5 on 2025-08-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_project_owner_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code pays'),
        ),
        migrations.AddField(
            model_name='vote',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='project',
            name='platform_status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('desactive', 'Désactivé'), ('rejete', 'Rejeté'), ('publie', 'Publié')], default='brouillon', max_length=100, verbose_name="L'admin défini sur :"),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(choices=[(1, '1 Vote'), (2, '2 Votes'), (3, '3 Votes'), (4, '4 Votes'), (5, '5 Votes')], verbose_name='Nombre de vote'),
        ),
    ]
