import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AppInitialiser from "./(dashboard)/AppInitialiser";
import { AuthWatcher } from "./(dashboard)/admin/AuthWatcher";
import Script from "next/script";
import Providers from "./providers";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Project awards",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.variable}`}>
      <body className="font-outfit ">
        <Providers>
          <main className=" ">{children}</main>
          <Toaster richColors position="top-right" />
        </Providers>
        <Script
          src="https://cdn.fedapay.com/checkout.js?v=1.1.7"
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
