events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name projectawards.scarsoft.net;
        
        # Pour Let's Encrypt
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
            try_files $uri $uri/ =404;
        }
        
        # Réponse temporaire pour les autres requêtes
        location / {
            return 200 'Server is setting up SSL...';
            add_header Content-Type text/plain;
        }
    }
}
