# Generated by Django 5.2.5 on 2025-09-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Cet email est déjà utilisé......'}, max_length=254, unique=True),
        ),
    ]
