# Generated by Django 5.2.5 on 2025-08-21 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='default.jpg', null=True, upload_to='owner-files')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('country_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code pays')),
                ('profession', models.TextField(blank=True, null=True, verbose_name='Profession')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.commercial', verbose_name='Commercial affilié')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
