# Generated by Django 5.2.5 on 2025-09-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectowner', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='accept_project_reformulation',
            field=models.BooleanField(default=False, verbose_name="J'accepte que mon projet soit reformulé par l'équipe Project Awards selon les critères du site."),
        ),
        migrations.AddField(
            model_name='owner',
            name='accept_terms_of_use',
            field=models.BooleanField(default=False, verbose_name="J'ai lu et j'accepte les conditions d'utilisation."),
        ),
    ]
