# Generated by Django 5.2.5 on 2025-09-23 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectowner', '0002_initial'),
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauths.profile'),
        ),
    ]
