# Generated by Django 5.2.5 on 2025-08-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectowner', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
        migrations.AddField(
            model_name='owner',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code pays'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Nom complet'),
        ),
    ]
