# Generated by Django 5.2.5 on 2025-08-20 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_progress_report_project_target_audience'),
        ('projectowner', '0003_owner_age_owner_country_code_alter_owner_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.commercial', verbose_name='Commercial affilié'),
        ),
    ]
