# Generated by Django 5.2.5 on 2025-09-23 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectowner', '0003_owner_profile'),
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='userauths.profile'),
        ),
    ]
