version = 5.2.2
archive_dir = /etc/letsencrypt/archive/projectawards.scarsoft.net
cert = /etc/letsencrypt/live/projectawards.scarsoft.net/cert.pem
privkey = /etc/letsencrypt/live/projectawards.scarsoft.net/privkey.pem
chain = /etc/letsencrypt/live/projectawards.scarsoft.net/chain.pem
fullchain = /etc/letsencrypt/live/projectawards.scarsoft.net/fullchain.pem
[renewalparams]
account = 0c300f961685c7cdf1b34a5c76ad3e6c
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
projectawards.scarsoft.net = /var/www/certbot
